### PR TITLE
Fixes and improvements 

### PR DESCRIPTION
**Pull request by humanshield89**
* Fix some bugs and miss functions
*  changed the way we store the per user fuel 
*  improved the structure of the transfer function
* added an escrow only burn function that will be used after the crash to burn all excess token

@LunarAI LGTM !

### CODE REVIEW

**Comment by LunarAI** [comment]
@humanshield89 lgtm

**Review by LunarAI — APPROVED** [review]
Thank you for adding the escrow in here. The changes look great and all the tests pass.
Once we are happy with everything, I will move the needed functions over to Volume.

I will also add the tests for the escrow and LP pool now, so hold on before you merge.

**Comment by humanshield89** [comment]
@LunarAI I just noticed that the owner is redundant here and has no purpose what so ever

**Comment by LunarAI** [comment]
> @LunarAI I just noticed that the owner is redundant here and has no purpose what so ever

Yeah, we would have used it, but the escrow replaces that functionality. I want to add one change here so just pull within the next 5 mins first if you plan on doing anything else.

**Comment by humanshield89** [comment]
@LunarAI I restructured the Volume and the TestVolume

**Comment by humanshield89** [comment]
All changes in here are included in the Pre-release branch 
so this PR is moot at this point

**Pull request closed without merging**
